---@meta _

---@alias AdapterID string
---
---@class Adapter
---@field api_version string Semantic version (e.g., '1.0.0')
---@field init fun(config: AdapterConfig): boolean Initialize the adapter
---@field cleanup fun() Cleanup adapter resources
---
---@class AdapterConfig
---@field id string Unique identifier for this adapter instance
---@field display_name string Human-readable name for UI display
---@field type 'jellyfin'|'emby'|'plex'|'subsonic'|'other' Adapter type
---@field external? boolean Whether this adapter is external or not (default: false)
---@field enabled? boolean Whether this adapter should be loaded (default: true)
---@field url? string Base URL for the media server
---@field username? string Username for authentication
---@field password? string Password for authentication
---@field file_path? string Path to external adapter script (overrides default path)
---
---@alias MediaType 'video'|'audio'|'other'
---
---Represents event mappings between the content controller and an adapter.
---@class AdapterEventMap
---@field request string
---@field navigate_to string
---@field search? string
---@field action? string
---@field status? string
---@field error? string
---
---Represents the capabilities supported by an Adapter.
---@class AdapterCapabilities
---@field supports_search boolean
---@field supports_thumbnails boolean
---@field media_types MediaType[]
---
---Represents the Adapter API for communication between adapters, and the content controller.
---@class AdapterAPI
---@field adapter_id AdapterID
---@field adapter_name string Human readable adapter name.
---@field adapter_type 'jellyfin'|'plex'|'emby'|'subsonic'|'other'
---@field events AdapterEventMap
---@field capabilities AdapterCapabilities
---
---Represents the adapter state
---@class AdapterState
---@field config AdapterConfig?
---@field auth_in_progress boolean
---@field authenticated boolean
---@field auth_failed boolean
---@field api AdapterAPI
---
---Represents the data sent during an adapter request event.
---@class AdapterRequestData
---@field ctx_id NavCtxID 
---@field nav_id NavID
---@field adapter_id AdapterID
---
---Represents the data sent during an adapter navigate to event.
---@class AdapterNavToData
---@field ctx_id NavCtxID
---@field nav_id NavID
---@field adapter_id AdapterID 
---@field selection number
---
---Represents the data sent during an adapter error event.
---@class AdapterErrorData
---@field adapter_id AdapterID
---@field error? string 
