---@meta _
---
---@alias UiMode string
---@alias UiOverlay string
---
---@class UiModeData
---@field mode UiMode
---
---@class UiOverlayData
---@field overlay UiOverlay
---
---@class UiUpdateData
---@field cursor_pos? number
